owntube/urls.py
from django.conf.urls import patterns, include, url
from videoportal.feeds import *
from livestream.feeds import UpcomingEvents
from django.conf import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'videoportal.views.list'),
    url(r'^videos/(?P<slug>[-\w]+)/$', 'videoportal.views.detail'),
    url(r'^tags/(?P<tag>[\w|\W]+)/$', 'videoportal.views.tag'),
    url(r'^collection/(?P<slug>[-\w]+)/$', 'videoportal.views.collection'),
    url(r'^json_tags/(?P<tag>[\w|\W]+)/$', 'videoportal.views.tag_json'),
    url(r'^videos/channel/(?P<slug>[-\w]+)/$', 'videoportal.views.channel_list'),
    url(r'^videos/iframe/(?P<slug>[-\w]+)/$', 'videoportal.views.iframe'),
    url(r'^search/', 'videoportal.views.search'),
    url(r'^json_search/', 'videoportal.views.search_json'),
    url(r'^submit/', 'videoportal.views.submit'),
    url(r'^encodingdone/', 'videoportal.views.encodingdone'),
    url(r'^status/', 'videoportal.views.status'),
    url(r'^contact/', 'static_pages.views.contact'),
    url(r'^about/', 'static_pages.views.about'),
    url(r'^stream/$', 'livestream.views.current'),
    url(r'^stream/list/$', 'livestream.views.list'),
    url(r'^stream/(?P<slug>[-\w]+)/$', 'livestream.views.detail'),
    url(r'^login/', 'django.contrib.auth.views.login'),
    url(r'^logout/', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^feeds/latest/mp4', LatestMP4Videos()),
    url(r'^feeds/latest/webm', LatestWEBMVideos()),
    url(r'^feeds/latest/mp3', LatestMP3Audio()),
    url(r'^feeds/latest/ogg', LatestOGGAudio()),
    url(r'^feeds/stream/upcoming', UpcomingEvents()),
    url(r'^feeds/latest/torrent', TorrentFeed()),
    url(r'^feeds/(?P<channel_slug>[-\w]+)/mp4/$', ChannelFeedMP4()),
    url(r'^feeds/(?P<channel_slug>[-\w]+)/webm/$', ChannelFeedWEBM()),
    url(r'^feeds/(?P<channel_slug>[-\w]+)/ogg/$', ChannelFeedOGG()),
    url(r'^feeds/(?P<channel_slug>[-\w]+)/mp3/$', ChannelFeedMP3()),
    url(r'^feeds/(?P<channel_slug>[-\w]+)/torrent/$', ChannelFeedTorrent()),
    url(r'^feeds/collection/(?P<collection_slug>[-\w]+)/mp4/$', CollectionFeedMP4()),
    url(r'^feeds/collection/(?P<collection_slug>[-\w]+)/webm/$', CollectionFeedWEBM()),
    url(r'^feeds/collection/(?P<collection_slug>[-\w]+)/ogg/$', CollectionFeedOGG()),
    url(r'^feeds/collection/(?P<collection_slug>[-\w]+)/mp3/$', CollectionFeedMP3()),
    url(r'^feeds/collection/(?P<collection_slug>[-\w]+)/torrent/$', CollectionFeedTorrent()),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

videoportal/models.py
from django.db import models
from django.contrib.auth.models import User

from autoslug import AutoSlugField
from taggit.managers import TaggableManager

import appsettings as settings

from pytranscode.ffmpeg import *
from pytranscode.presets import *
from pytranscode.runner import *

import os
import subprocess
import re
import decimal 
from mutagen import File

import urllib2
import datetime
import os
import re
from threading import Event

from BitTornadoABC.btmakemetafile import calcsize, make_meta_file, ignore

KIND_CHOICES = (
    (0, 'Video-only'),
    (1, 'Audio-only'),
    (2, 'Audio & Video'),
)

class Video(models.Model):
    ''' The model for our videos. It uses slugs (with DjangoAutoSlug) and tags (with Taggit)
    everything else is quite standard. The sizes fields are used in the feeds to make enclosures
    possible. The videoThumbURL is the URL for Projekktor's "poster" and assemblyid is just a storage
    for the result we get back from transloadit so that we know which video just triggered the "encoding_done"
    view. Why are there URL fields and not file fields? Because you maybe want to use external storage
    (like Amazon S3) to store your files '''

    created = models.DateTimeField(auto_now_add=True)
    channel = models.ForeignKey('videoportal.Channel',blank=True,null=True)
    date = models.DateField("Datum")
    description = models.TextField(u"Beschreibung")
    linkURL = models.URLField("Link",blank=True,verify_exists=False)
    modified = models.DateTimeField(auto_now=True)
    originalFile = models.FileField("Datei",upload_to="raw/%Y/%m/%d/", max_length=2048)
    tags = TaggableManager("Tags")
    title = models.CharField(u"Titel",max_length=200)

    assemblyid = models.CharField("Transloadit Result",max_length=100,blank=True)
    audioThumbURL = models.URLField("Audio Cover-URL",blank=True,verify_exists=False)
    autoPublish = models.BooleanField(default=True)
    duration = models.DecimalField(null=True, max_digits=10, decimal_places=2,blank=True)
    encodingDone = models.BooleanField()
    kind = models.IntegerField("Art",max_length=1, choices=KIND_CHOICES)
    mp4URL = models.URLField("MP4-URL",blank=True,verify_exists=False)
    mp4Size = models.BigIntegerField("MP4 Size in Bytes",null=True,blank=True)
    mp3URL = models.URLField("MP3-URL",blank=True,verify_exists=False)
    mp3Size = models.BigIntegerField("MP3 Size in Bytes",null=True,blank=True)
    oggURL = models.URLField("OGG-URL",blank=True,verify_exists=False)
    oggSize = models.BigIntegerField("OGG Size in Bytes",null=True,blank=True)
    published = models.BooleanField()
    slug = AutoSlugField(populate_from='title',unique=True)
    torrentURL = models.URLField("Torrent-URL",blank=True,verify_exists=False)
    torrentDone = models.BooleanField()
    user = models.ForeignKey(User, blank=True, null=True)
    videoThumbURL = models.URLField("Video Thumb-URL",blank=True,verify_exists=False)
    webmURL = models.URLField("WEBM-URL",blank=True,verify_exists=False)
    webmSize = models.BigIntegerField("WEBM Size in Bytes",null=True,blank=True)

    def __unicode__(self):
        return self.title
    def get_absolute_url(self):
        return "/videos/%s/" % self.slug
    def getClassName(self):
        return self.__class__.__name__

    def encode_media(self):
        ''' This is used to tell ffmpeg what to do '''
        kind = self.kind
        path = self.originalFile.path
        outputdir = settings.ENCODING_OUTPUT_DIR + self.slug
        if not os.path.exists(outputdir):
            os.makedirs(outputdir)
        outputdir = outputdir + '/'
        if ((kind == 0) or (kind == 2)):
            logfile = outputdir + 'encoding_mp4_log.txt'
            outfile_mp4 = outputdir + self.slug + '.mp4'
            # Create the command line
            cl_mp4 = ffmpeg(path, outfile_mp4, logfile, OWNTUBE_MP4_VIDEO, OWNTUBE_MP4_AUDIO).build_command_line()
            
            logfile = outputdir + 'encoding_webm_log.txt'
            outfile_webm = outputdir + self.slug + '.webm'
    
            cl_webm = ffmpeg(path, outfile_webm, logfile, OWNTUBE_WEBM_VIDEO, OWNTUBE_WEBM_AUDIO).build_command_line()
            
            self.mp4URL = settings.ENCODING_VIDEO_BASE_URL + self.slug + '/' + self.slug + '.mp4'
            self.webmURL = settings.ENCODING_VIDEO_BASE_URL + self.slug + '/' + self.slug + '.webm' 
            self.videoThumbURL = settings.ENCODING_VIDEO_BASE_URL + self.slug + '/' + self.slug + '.jpg'
            outcode = subprocess.Popen(cl_mp4, shell=True)
            
            while outcode.poll() == None:
                pass
    
            if outcode.poll() == 0:
                self.mp4Size = os.path.getsize(outfile_mp4)
                self.duration = getLength(outfile_mp4)
            else:
                raise StandardError('Encoding MP4 Failed')
            
            print(cl_mp4)
            print(cl_webm)    
            outcode = subprocess.Popen(cl_webm, shell=True)
            
            while outcode.poll() == None:
                pass
    
            if outcode.poll() == 0:
                self.wembSize = os.path.getsize(outfile_webm)
            else:
                raise StandardError('Encoding WEBM Failed')
    
            outcode = subprocess.Popen(['/usr/local/bin/ffmpeg -i '+ self.originalFile.path + ' -ss 5.0 -vframes 1 -f image2 ' + outputdir + self.slug + '.jpg'],shell = True)
            
            while outcode.poll() == None:
                pass
    
            if outcode.poll() == 0:
                pass 
            else:
                raise StandardError('Making Thumb Failed')
            
            
        if((kind == 1) or (kind == 2)):
            logfile = outputdir + 'encoding_mp3_log.txt'
            outfile_mp3 = outputdir + self.slug + '.mp3'
            # Create the command line
            cl_mp3 = ffmpeg(path, outfile_mp3, logfile, OWNTUBE_NULL_VIDEO , OWNTUBE_MP3_AUDIO).build_command_line()
            
            logfile = outputdir + 'encoding_ogg_log.txt'
            outfile_ogg = outputdir + self.slug + '.ogg'

            cl_ogg = ffmpeg(path, outfile_ogg, logfile, OWNTUBE_NULL_VIDEO, OWNTUBE_OGG_AUDIO).build_command_line()
            
            self.mp3URL = settings.ENCODING_VIDEO_BASE_URL + self.slug +  '/' + self.slug + '.mp3'
            self.oggURL = settings.ENCODING_VIDEO_BASE_URL + self.slug +  '/' + self.slug + '.ogg'
            
            outcode = subprocess.Popen(cl_mp3, shell=True)
            
            while outcode.poll() == None:
                pass
    
            if outcode.poll() == 0:
                self.mp3Size = os.path.getsize(outfile_mp3)
                self.duration = getLength(outfile_mp3)
            else:
                raise StandardError('Encoding MP3 Failed')
                
            outcode = subprocess.Popen(cl_ogg, shell=True)
            
            while outcode.poll() == None:
                pass
    
            if outcode.poll() == 0:
                self.oggSize = os.path.getsize(outfile_ogg)
            else:
                raise StandardError('Encoding OGG Failed')
                
        if (kind == 1):
            file = File(self.originalFile.path) # mutagen can automatically detect format and type of tags
            if file.tags and 'APIC:' in file.tags and file.tags['APIC:']:
                artwork = file.tags['APIC:'].data # access APIC frame and grab the image
                with open(outputdir + self.slug + '_cover.jpg', 'wb') as img:
                    img.write(artwork)

                self.audioThumbURL = settings.ENCODING_VIDEO_BASE_URL + self.slug + '/' + self.slug + '_cover.jpg'

        self.encodingDone = True
        self.torrentDone = settings.USE_BITTORRENT
        if settings.USE_BITTORRENT:
            self.torrentURL = settings.BITTORRENT_FILES_BASE_URL + self.slug + '.torrent'
            
        self.published = self.autoPublish
        self.save()
        
    def create_bittorrent(self):
        ''' This is where the bittorrent files are created and transmission is controlled'''
        flag = Event()
        make_meta_file(str(self.originalFile.path),
            settings.BITTORRENT_TRACKER_ANNOUNCE_URL,
            params = {'target' : settings.BITTORRENT_FILES_DIR
                                            + self.slug + '.torrent',
             'piece_size_pow2' : 18,
             'announce_list': settings.BITTORRENT_TRACKER_BACKUP,
             'url_list' : str(self.originalFile.url)},
             flag = flag,
             progress_percent=0)
        self.torrentURL = settings.BITTORRENT_FILES_BASE_URL + self.slug + '.torrent'
        self.torrentDone = True
        self.published = self.autoPublish
        self.save()
        
class Comment(models.Model):
    ''' The model for our comments, please note that (right now) OwnTube comments are moderated only'''
    name = models.CharField(u"Name",max_length=30)
    ip = models.IPAddressField("IP",blank=True,null=True)
    moderated = models.BooleanField()
    timecode = models.DecimalField(null=True, max_digits=10, decimal_places=2,blank=True)
    comment = models.TextField(u"Kommentar", max_length=1000)
    video = models.ForeignKey(Video)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return self.comment

class Channel(models.Model):
    ''' The model for our channels, all channels can hold videos but videos can only be part of one channel'''
    name = models.CharField(u"Name",max_length=30)
    slug = AutoSlugField(populate_from='name',unique=True)
    description = models.TextField(u"Beschreibung", max_length=1000, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    featured = models.BooleanField()
    def __unicode__(self):
        return self.name

    def get_absolute_url(self):

templates/videos/collection.html
{% extends "base.html" %}
{% block active1 %}
class="active"
{% endblock %}
{% load custom_filters %}
{% block body %}
<div class="page-header">
<h1>Playlist: {{ collection.title }}</h1>
</div>
<div class="row">
<div class="span8">
{% include "videos/videolist.html" with video_list=videos_list %}
</div>
<div class="span4">
<div class=well>
<ul class="nav nav-list">
  <li class="nav-header">
    Original Material
  </li>
  <li>
    <a href="/feeds/collection/{{ collection.slug }}/torrent/"">Torrents-Feed</a>
  </li>
  <li class="nav-header">
    Video-Podcast
  </li>
  <li>
    <a href="/feeds/collection/{{ collection.slug }}/mp4/">MP4-Format</a>
  </li>
  <li>
    <a href="/feeds/collection/{{ collection.slug }}/webm/">WEBM-Format</a>
  </li>
  <li class="nav-header">
    Audio-Podcast
  </li>
  <li>
    <a href="/feeds/collection/{{ collection.slug }}/mp3/">MP3-Format</a>
  </li>
  <li>
    <a href="/feeds/collection/{{ collection.slug }}/ogg/">OGG-Format</a>
  </li>
</ul>
</div>
</div>
	</div>
{% endblock %}

templates/videos/detail.html
{% extends "base.html" %}
{% load custom_filters %}
{% load markup %}
{% block title %} - {{ video.title }}{% endblock %}
{% block head %}
<script type="text/javascript" src="{{ STATIC_URL }}projekktor/projekktor.min.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}projekktor/theme/style.css" type="text/css" media="screen" />
{% endblock %}
{% block active1 %}class="active"{% endblock %}
{% block body %}
<div class="page-header">
<h1>{{ video.title }}</h1>
</div>
<div class="row">
<div class="span8">
  {% if video.kind == 0 %}
  <div class="row">
    <div class="span8">
      <video id="player_a" class="projekktor" poster="{{ video.videoThumbURL }}" title="{{ video.title }}" width="640" height="360" controls>
        {% if video.webmURL %}<source src="{{ video.webmURL }}" type="video/webm" />{% endif %}
        {% if video.mp4URL %}<source src="{{ video.mp4URL }}" type="video/mp4" />{% endif %}
      </video>
    </div>
  </div>
  {% endif %}
  {% if video.kind == 1 %}
  <div class="row">
    <div class="span8">
	  <audio id="player_b" class="projekktor" title="{{ video.title}}" width="640" height="360" poster="{% if video.audioThumbURL %}{{ video.audioThumbURL }} {% else %} {{ STATIC_URL }}audio_cover.png {% endif %}" controls>
	    {% if video.mp3URL %}<source src="{{ video.mp3URL }}" type="audio/mp3" />{% endif %}
        {% if video.oggURL %}<source src="{{ video.oggURL }}" type="application/ogg" />{% endif %}
      </audio>
    </div>
  </div>
  {% endif %}
  {% if video.kind == 2 %}
  <div class="row">
    <div class="span8">
      <ul class="nav nav-tabs">
        <li class="active" id="video_tab"><a>Video</a></li>
        <li  id="audio_tab"><a>Audio</a></li>
      </ul>
      <div id="player_container">
        <div id="video_player">
          <video id="player_a" class="projekktor" poster="{{ video.videoThumbURL }}" title="{{ video.title }}" width="640" height="360" controls>
            {% if video.webmURL %}<source src="{{ video.webmURL }}" type="video/webm" />{% endif %}
            {% if video.mp4URL %}<source src="{{ video.mp4URL }}" type="video/mp4" />{% endif %}
          </video>
        </div>
        <div id="audio_player" style="display:none;">
          <audio id="player_b" class="projekktor" title="{{ video.title}}" width="640" height="360" poster="{% if video.audioThumbURL %}{{ video.audioThumbURL }} {% else %} {{ STATIC_URL }}audio_cover.png {% endif %}" controls>
	        {% if video.mp3URL %}<source src="{{ video.mp3URL }}" type="audio/mp3" />{% endif %}
            {% if video.oggURL %}<source src="{{ video.oggURL }}" type="application/ogg" />{% endif %}
          </audio>'
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  <div class="row">
  <div class="span8">
  <h2>Kommentare</h2>
  {% if comments %}
  {% for comment in comments %}
  <div class="row">
  <div class="span8">
  <div class="well">
  <strong>Name: </strong>{{ comment.name }} {% if comment.timecode %} &bull; <strong>Zeit: </strong><a class="timecode">{{ comment.timecode }}</a>{% endif %}
  <div class="comment-body">
  {{ comment.comment }}
  </div>
  </div>
  </div>
  </div>
  {% endfor %}
  {% else %}
  <div class="row">
  <div class="span8">
  <div class="well">
  <p>Bis jetzt keine Kommentare</p>
  </div>
  </div>
  </div>
  {% endif %}
  {% if message %}
  <div class="alert">
  {{ message }}
  </div>
  {% endif %}
  <form enctype="multipart/form-data" class="form-horizontal" action="/videos/{{ video.slug }}/" method="post">{% csrf_token %}
    {% for field in comment_form %}
    	<div class="control-group">
    		{% if field.errors %}
    		<div class="alert alert-error">
				<strong>Fehler! </strong>{{ field.errors }}
			</div>
    		{% endif %}
			<div class="control-label">
        	{{ field.label_tag }}
        	</div>
        	<div class="controls">
        	{{ field }}
        	</div>
        </div>
    {% endfor %}
<div class="form-actions">
<input type="submit" class="btn btn-primary" value="Senden" />
</div>
</form>
  </div>
  </div>
  </div>
  <div class="span4">
  <div class="well">
  <dl>
  <dt>Datum</dt>
  <dd>{{ video.date }}</dd>
  <dt>Beschreibung<dt>
  <dd><div style="max-height:200px; overflow-y: scroll;">{{ video.description|markdown:"safe" }}</div></dd>
  {% if video.channel %}
  <dt>Channel</dt>
  <dd><a href="/videos/channel/{{ video.channel.slug }}/">{{ video.channel.name }}</a>
  {% endif %}
  {% if video.user %}
  <dt>Hochgeladen von</dt>
  {% if video.user.first_name %}
  <dd>{{ video.user.first_name }} {{ video.user.last_name }}</dd>
  {% else %}
  <dd>{{ video.user }}
  {% endif %}
  {% endif %}
  {% if video.linkURL %}
  <dt>Link:</dt>
  <dd><a href="{{ video.linkURL }}" target="_Blank">{{ video.linkURL|truncatechars:40 }}</a></dd>
  {% endif %}
  <dt>Einbetten:</dt>
  <dd><input type="text" readonly="readonly" value='<iframe width="640" height="360" src="http://owntube.piratenfraktion-berlin.de/videos/iframe/{{ video.slug }}/" frameborder="0"></iframe>'></dd>
  {% if video.duration %}
  <dt>Dauer:</dt>
  <dd>{{ video.duration|secondstohms }}</dd>
  {% endif %}
  {% if video.torrentURL %}
  <dt>Torrent:</dt>
  <dd><a href="{{ video.torrentURL }}">Download Original</a></dd>
  {% endif %}
  <dt>Download:</dt>
  {% if video.mp4URL %}<dd><a href="{{ video.mp4URL }}">Download MP4 Video</a></dd>{% endif %}
  {% if video.webmURL %}<dd><a href="{{ video.webmURL }}">Download WEBM Video</a></dd>{% endif %}
  {% if video.mp3URL %}<dd><a href="{{ video.mp3URL }}">Download MP3 Audio</a></dd>{% endif %}
  {% if video.oggURL %}<dd><a href="{{ video.oggURL }}">Download OGG Audio</a></dd>{% endif %}
  </div>
  <div class="well">
  <ul>
        {% for tag in video.tags.all %}
            <li><a href="/tags/{{ tag.name }}/">{{ tag.name }}</a></li>
        {% endfor %}
  </ul>
  </div>
  </div>
{% endblock %}
{% block javascript %}
<script type="text/javascript">
         $(document).ready(function() {
         	   var timeListener = function(value) {	
					$('#id_timecode').val( value.toFixed(2) )
  				}
               {% if video.kind == 0 or video.kind == 2 %}
               var video_player = projekktor('#player_a', {
	                /* path to the MP4 Flash-player fallback component */
	                playerFlashMP4:		'{{ STATIC_URL }}projekktor/jarisplayer.swf',
	        
	                /* path to the MP3 Flash-player fallback component */
	                playerFlashMP3:		'{{ STATIC_URL }}projekktor/jarisplayer.swf',
                        streamType: 'http',
               });
               
               video_player.addListener('time', timeListener);
               
               {% endif %}
               {% if video.kind == 1 or video.kind == 2 %}
               var audio_player = projekktor('#player_b', {
	                /* path to the MP4 Flash-player fallback component */
	                playerFlashMP4:		'{{ STATIC_URL }}projekktor/jarisplayer.swf',
	        
	                /* path to the MP3 Flash-player fallback component */
	                playerFlashMP3:		'{{ STATIC_URL }}projekktor/jarisplayer.swf',
                        streamType: 'http',
               });
               
               audio_player.addListener('time', timeListener);
               {% endif %}
			  $('.timecode').click(function(){
			    console.log(this.text);
			  	video_player.setPlayhead(parseFloat(this.text)); 
			  	audio_player.setPlayhead(parseFloat(this.text));
			  	return false;
			  	})
			  
         });         
$('#video_tab a').click(function (e) {
  e.preventDefault();
  $(this).tab('show');
  $('#video_player').toggle();
  $('#audio_player').toggle();
})
$('#audio_tab a').click(function (e) {
  e.preventDefault();
  $(this).tab('show');
  $('#video_player').toggle();
  $('#audio_player').toggle();
})
</script>
{% endblock %}

templates/videos/list.html
{% extends "base.html" %}
{% block active1 %}
class="active"
{% endblock %}
{% load custom_filters %}
{% block body %}
<div class="page-header">
<h1>Tag: {{ tag }}</h1>
</div>
<div class="row">
<div class="span8">
{% include "videos/videolist.html" with video_list=videos_list %}
</div>
<div class="span4">
<div class=well>
<ul class="nav nav-list">
  <li class="nav-header">
    Original Material
  </li>
  <li>
    <a href="/feeds/latest/torrent/"">Torrents-Feed</a>
  </li>
  <li class="nav-header">
    Video-Podcast
  </li>
  <li>
    <a href="/feeds/latest/mp4/">MP4-Format</a>
  </li>
  <li>
    <a href="/feeds/latest/webm/">WEBM-Format</a>
  </li>
  <li class="nav-header">
    Audio-Podcast
  </li>
  <li>
    <a href="/feeds/latest/mp3/">MP3-Format</a>
  </li>
  <li>
    <a href="/feeds/latest/ogg/">OGG-Format</a>
  </li>
  <li class="divider"></li>
  <li>
  	<a href="mailto:pbrechler@mac.com"><i class="icon-bullhorn"></i> Kontakt</a>
  </li>
</ul>
</div>
</div>
	</div>
{% endblock %}

templates/videos/nothing.html
{% extends "base.html" %}
{% block body %}
<p>Nothing to see here, move along</p>
{% endblock %}

templates/videos/submit.html
{% extends "base.html" %}
{% block active5 %}
class="active"
{% endblock %}
{% block title %} - Hochladen{% endblock %}
{% block head %}
<script type="text/javascript" src="{{ STATIC_URL }}jquery.form.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}date.format.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}jquery.validate.min.js"></script>

{% endblock %}
{% block body %}
<div class="page-header">
<h1>Hochladen</h1>
</div>
<div class=row">
<div class="span6">
<form id="videoForm" enctype="multipart/form-data" class="form-horizontal" action="/submit/" method="post">{% csrf_token %}
    {% for field in submit_form %}
    	<div class="control-group">
    		{% if field.errors %}
    		<div class="alert alert-error">
				<strong>Fehler! </strong>{{ field.errors }}</p>
			</div>
    		{% endif %}
			<div class="control-label">
        	{{ field.label_tag }}
        	</div>
        	<div class="controls">
        	{{ field }}
            {% if field.field.required %}
            *
            {% endif %}
        	</div>
        </div>
    {% endfor %}
    <div id="progress-indicator">
	<div class="progress progress-striped active">
        <div class="bar"></div >
	</div>
	<div class="percent">0%</div >
	</div>
<div class="form-actions">
<input type="submit" class="btn btn-primary" value="Hochladen" />
</div>
</form>
</div>
</div>
{% endblock %}
{% block javascript %}
<script>
$(document).ready(function() {

  var now = new Date();
  var formatted = now.format("dd.mm.yyyy");
  $('#id_date').val(formatted);
  $('#progress-indicator').hide();
  var bar = $('.bar');
  var percent = $('.percent');
  $('#videoForm').validate({
      rules: {
        {% for field in submit_form %}
        {% if field.field.required %}
        {{ field.name }}: "required",
        {% endif %}
        {% endfor %}
  }})

  $('#videoForm').ajaxForm({
    beforeSubmit: function() { return $('#videoForm').valid() },
    beforeSend: function() {
                $('#progress-indicator').show();
        var percentVal = '0%';
        bar.width(percentVal)
        percent.html(percentVal);
    },
    uploadProgress: function(event, position, total, percentComplete) {
        var percentVal = percentComplete + '%';
        bar.width(percentVal)
        percent.html(percentVal);
        document.title = 'OwnTube - Hochladen - ' + percentVal;
    },
        complete: function(xhr) {
                if (xhr.status == 200){
                        alert("Danke, ihr Video wird trancodiert und sollte bald zur Verfügung stehen");
                        window.location.href = "/status/";
                }else {
                        alert("Tut uns leid, das hat nicht geklappt, bitte noch mal versuchen oder den Admin nerven");
                }
        }
  });
});
</script>
{% endblock %}